remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Olivier MARY]
age: [38 ans]
mail: [olivier.mary.31@gmail.com]
description: [CV Olivier MARY]
pdf_url: https://github.com/OlivierMary/oliviermary.github.io/raw/master/oliviermary_github.pdf
show_downloads: false
lang: [fr-FR]
